set foreign_key_checks =0;

delete from t_deduct_application;
delete from t_product_category;
delete from t_source_repository;


INSERT INTO `t_deduct_application` (`id`, `deduct_application_uuid`, `deduct_id`, `request_no`, `financial_contract_uuid`, `financial_product_code`, `contract_unique_id`, `repayment_plan_code_list`, `contract_no`, `planned_deduct_total_amount`, `actual_deduct_total_amount`, `notify_url`, `transcation_type`, `repayment_type`, `execution_status`, `execution_remark`, `create_time`, `creator_name`, `ip`, `last_modified_time`, `record_status`, `is_available`, `api_called_time`, `transaction_recipient`, `customer_name`, `mobile`, `gateway`, `source_type`, `third_part_voucher_status`, `complete_time`, `transaction_time`, `actual_notify_number`, `plan_notify_number`, `batch_deduct_application_uuid`, `batch_deduct_id`, `none_business_check_status`, `business_check_status`, `notify_status`, `retriable`, `retry_times`, `payment_order_uuid`, `version`)
VALUES
	(17, 'e3f10f17-f598-4242-9ab5-0738787d3b76', '33175be0-8a7d-4aef-89e0-3c32834d5690', '0df4ad92-47fa-46d4-9e00-f7ad5b2c0d5f', 'd2812bc5-5057-4a91-b3fd-9019506f0499', 'G31700', NULL, NULL, NULL, 100.01, 0.00, '', 1, NULL, 1, '', '2017-06-10 10:52:57', 't_test_zfb', '127.0.0.1', '2017-06-10 10:52:57', 0, 0, NULL, 1, NULL, NULL, NULL, 1, 0, NULL, '2017-06-10 10:52:57', NULL, NULL, NULL, NULL, 0, 0, 0, 0, NULL, NULL, NULL);

INSERT INTO `t_source_repository` ( `business_type`, `source_code`, `signature`, `source_file_path`, `add_time`, `last_modify_time`, `author`)
VALUES
	( 'zhonghang/deduct-business-acceptance', '	@Override\n	public boolean evaluate(SandboxDataSetHandler sandboxDataSetHandler,\n			Map<String, String> preRequest, Map<String, String> postRequest,\n			Log logger) {\n		\n		String financialProductCode = (String)preRequest.getOrDefault(\"financialProductCode\", StringUtils.EMPTY);\n		\n		String accountName = (String)preRequest.getOrDefault(\"accountName\", StringUtils.EMPTY);\n    	\n    	String accountNo = (String)preRequest.getOrDefault(\"accountNo\", StringUtils.EMPTY);\n    	\n        FinancialContract financialContract = sandboxDataSetHandler.getFinancialContractByProductCode(financialProductCode);\n        \n        if(financialContract == null){\n        	\n        	postRequest.put(\"errorMsg\",\"信托合同不存在\");\n		      \n 		    return false;\n        }\n        \n        String financialContractUuid = (financialContract.getFinancialContractUuid());\n        \n    	SandboxDataSet sandboxDataSet = sandboxDataSetHandler.getSandbox_for_signup(accountName, accountNo, SignUpStatus.SUCCESS, financialProductCode);\n\n    	Map<String,String> extraData =  sandboxDataSet.getExtraData();\n	      \n    	String signUpJsonString = (String)extraData.get(\"signUps\");\n	      //transfer to standardCode\n    	List<SignUp> signUpList = (List<SignUp>)JsonUtils.parseArray(signUpJsonString, SignUp.class);\n    	\n    	if(CollectionUtils.isEmpty(signUpList)){\n    		\n    	    postRequest.put(\"errorMsg\",\"未获取到授权信息\");\n		      \n		    return false;\n    	}\n    	\n    	List<PaymentChannelAndSignUpInfo> paymentChannelAndSignUpInfos = (List<PaymentChannelAndSignUpInfo>) sandboxDataSetHandler.getPaymentChannelAndSignUpInfoBy(financialContractUuid, signUpList);\n    	\n    	postRequest.put(\"financialContractUuid\", financialContractUuid);\n    	postRequest.put(\"paymentChannelAndSignUpInfoString\", JsonUtils.toJsonString(paymentChannelAndSignUpInfos));\n				\n		return true;\n	}', '44cc00df-6933-11e7-aa70-525400dbb013', NULL, '2017-07-15 05:52:02', '2017-07-15 05:52:02', 'sys');

INSERT INTO `t_product_category` ( `uuid`, `product_lv_1_code`, `product_lv_1_name`, `product_lv_2_code`, `product_lv_2_name`, `product_lv_3_code`, `product_lv_3_name`, `pre_process_interface_url`, `post_process_interface_url`, `pre_process_script`, `status`, `script_md_5_version`, `date_field_one`, `date_field_two`, `date_field_three`, `long_field_one`, `long_field_two`, `long_field_three`, `string_field_one`, `string_field_two`, `string_field_three`, `decimal_field_one`, `decimal_field_two`, `decimal_field_three`, `delay_task_config_uuid`)
VALUES
	('c6728386-4066-11e7-b482-a6072dcb76ed', 'zhonghang', '中航', 'DEDUCT', '扣款-业务验证', 'deduct-business-acceptance', '单扣', 'DEDUCT/zhonghang/deduct-business-acceptance', NULL, NULL, 1, 'e09dc8d4-4b5a-11e7-8be9-45d86c94a065', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


set foreign_key_checks =1;