/*
Date: 2016-06-23 17:49:59
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for trade_schedule
-- ----------------------------
DROP TABLE IF EXISTS `trade_schedule`;
CREATE TABLE `trade_schedule` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `access_version` varchar(255) DEFAULT NULL,
  `account_side` int(11) DEFAULT NULL,
  `business_status` int(11) DEFAULT NULL,
  `business_status_last_update_time` datetime DEFAULT NULL,
  `currency_code` varchar(255) DEFAULT NULL,
  `date_field_one` datetime DEFAULT NULL,
  `date_field_three` datetime DEFAULT NULL,
  `date_field_two` datetime DEFAULT NULL,
  `decimal_field_one` decimal(19,2) DEFAULT NULL,
  `decimal_field_three` decimal(19,2) DEFAULT NULL,
  `decimal_field_two` decimal(19,2) DEFAULT NULL,
  `destination_account_appendix` varchar(255) DEFAULT NULL,
  `destination_account_name` varchar(255) DEFAULT NULL,
  `destination_account_no` varchar(255) DEFAULT NULL,
  `destination_bank_info` varchar(255) DEFAULT NULL,
  `fif_business_failed_reason` varchar(255) DEFAULT NULL,
  `fif_business_status` int(11) DEFAULT NULL,
  `fif_communication_end_time` datetime DEFAULT NULL,
  `fif_communication_last_sent_time` datetime DEFAULT NULL,
  `fif_communication_start_time` datetime DEFAULT NULL,
  `fif_communication_status` int(11) DEFAULT NULL,
  `fif_gateway_router_info` varchar(255) DEFAULT NULL,
  `fif_gateway_router_result` varchar(255) DEFAULT NULL,
  `fif_gateway_type` int(11) DEFAULT NULL,
  `fif_schedule_info` varchar(255) DEFAULT NULL,
  `fif_transaction_amount` decimal(19,2) DEFAULT NULL,
  `fif_transaction_begin_time` datetime DEFAULT NULL,
  `fif_transaction_end_time` datetime DEFAULT NULL,
  `fourth_business_failed_reason` varchar(255) DEFAULT NULL,
  `fourth_business_status` int(11) DEFAULT NULL,
  `fourth_communication_end_time` datetime DEFAULT NULL,
  `fourth_communication_last_sent_time` datetime DEFAULT NULL,
  `fourth_communication_start_time` datetime DEFAULT NULL,
  `fourth_communication_status` int(11) DEFAULT NULL,
  `fourth_gateway_router_info` varchar(255) DEFAULT NULL,
  `fourth_gateway_router_result` varchar(255) DEFAULT NULL,
  `fourth_gateway_type` int(11) DEFAULT NULL,
  `fourth_schedule_info` varchar(255) DEFAULT NULL,
  `fourth_transaction_amount` decimal(19,2) DEFAULT NULL,
  `fourth_transaction_begin_time` datetime DEFAULT NULL,
  `fourth_transaction_end_time` datetime DEFAULT NULL,
  `fst_communication_end_time` datetime DEFAULT NULL,
  `fst_communication_last_sent_time` datetime DEFAULT NULL,
  `fst_communication_start_time` datetime DEFAULT NULL,
  `fst_communication_status` int(11) DEFAULT NULL,
  `fst_gateway_router_info` varchar(255) DEFAULT NULL,
  `fst_gateway_router_result` varchar(255) DEFAULT NULL,
  `fst_gateway_type` int(11) DEFAULT NULL,
  `fst_schedule_info` varchar(255) DEFAULT NULL,
  `fst_transaction_amount` decimal(19,2) DEFAULT NULL,
  `fst_transaction_begin_time` datetime DEFAULT NULL,
  `fst_transaction_end_time` datetime DEFAULT NULL,
  `fstbusiness_failed_reason` varchar(255) DEFAULT NULL,
  `fstbusiness_status` int(11) DEFAULT NULL,
  `long_field_one` bigint(20) NOT NULL,
  `long_field_three` bigint(20) NOT NULL,
  `long_field_two` bigint(20) NOT NULL,
  `out_lier_transaction_uuid` varchar(255) DEFAULT NULL,
  `postscript` varchar(255) DEFAULT NULL,
  `snd_business_status` int(11) DEFAULT NULL,
  `snd_communication_end_time` datetime DEFAULT NULL,
  `snd_communication_last_sent_time` datetime DEFAULT NULL,
  `snd_communication_start_time` datetime DEFAULT NULL,
  `snd_communication_status` int(11) DEFAULT NULL,
  `snd_gateway_router_info` varchar(255) DEFAULT NULL,
  `snd_gateway_router_result` varchar(255) DEFAULT NULL,
  `snd_gateway_type` int(11) DEFAULT NULL,
  `snd_schedule_info` varchar(255) DEFAULT NULL,
  `snd_transaction_amount` decimal(19,2) DEFAULT NULL,
  `snd_transaction_begin_time` datetime DEFAULT NULL,
  `snd_transaction_end_time` datetime DEFAULT NULL,
  `sndbusiness_failed_reason` varchar(255) DEFAULT NULL,
  `source_account_appendix` varchar(255) DEFAULT NULL,
  `source_account_name` varchar(255) DEFAULT NULL,
  `source_account_no` varchar(255) DEFAULT NULL,
  `source_bank_info` varchar(255) DEFAULT NULL,
  `source_message_ip` varchar(255) DEFAULT NULL,
  `source_message_time` datetime DEFAULT NULL,
  `source_message_uuid` varchar(255) DEFAULT NULL,
  `string_field_one` varchar(255) DEFAULT NULL,
  `string_field_three` varchar(255) DEFAULT NULL,
  `string_field_two` varchar(255) DEFAULT NULL,
  `trade_uuid` varchar(255) DEFAULT NULL,
  `trd_business_status` int(11) DEFAULT NULL,
  `trd_communication_end_time` datetime DEFAULT NULL,
  `trd_communication_last_sent_time` datetime DEFAULT NULL,
  `trd_communication_start_time` datetime DEFAULT NULL,
  `trd_communication_status` int(11) DEFAULT NULL,
  `trd_gateway_router_info` varchar(255) DEFAULT NULL,
  `trd_gateway_router_result` varchar(255) DEFAULT NULL,
  `trd_gateway_type` int(11) DEFAULT NULL,
  `trd_schedule_info` varchar(255) DEFAULT NULL,
  `trd_transaction_amount` decimal(19,2) DEFAULT NULL,
  `trd_transaction_begin_time` datetime DEFAULT NULL,
  `trd_transaction_end_time` datetime DEFAULT NULL,
  `trdbusiness_failed_reason` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of trade_schedule
-- ----------------------------
