SET FOREIGN_KEY_CHECKS=0;

delete from `t_external_trade_batch_detail`;

INSERT INTO `t_external_trade_batch_detail` (`id`, `external_trade_batch_detail_uuid`, `external_trade_batch_uuid`, `financial_contract_uuid`, `financial_contract_id`, `external_batch_no`, `external_record_sn`, `external_record_unique_id`, `external_business_order_no`, `amount`, `charges_detail`, `currency`, `cp_name`, `cp_bank_card_no`, `cp_bank_code_type`, `cp_bank_code`, `contract_unique_id`, `contract_no`, `repayment_plan_no`, `trade_time`, `trade_type`, `trade_remark`, `payment_gateway`, `external_trade_serial_no`, `cash_flow_serial_no`, `active_status`, `detail_verify_result`, `trade_audit_progress`, `trade_audit_result`, `trade_audit_result_remark`, `cash_flow_audit_result`, `cash_flow_audit_result_remark`, `create_time`, `last_modified_time`)
VALUES
	(2, 'external_trade_batch_detail_uuid1', 'external_trade_batch_uuid2', 'financial_contract_uuid', 1, 'external_batch_no', 'external_record_sn', 'external_record_unique_id', 'external_business_order_no', 11.00, NULL, 'currency', 'cp_name', 'cp_bank_card_no', 1, 'cp_bank_code', 'contract_unique_id', 'contract_no', 'repayment_plan_no', '2016-12-11 00:00:00', 1, 'trade_remark', 1, 'external_trade_serial_no', 'cash_flow_serial_no', 1, 1, 1, 1, 'trade_audit_result_remark', 1, 'cash_flow_audit_result_remark', '2016-10-22 00:00:00', '2016-11-11 00:00:00'),
	(3, 'external_trade_batch_detail_uuid2', 'external_trade_batch_uuid2', 'financial_contract_uuid', 1, 'external_batch_no', 'external_record_sn', 'external_record_unique_id', 'external_business_order_no', 11.00, NULL, 'currency', 'cp_name', 'cp_bank_card_no', 1, 'cp_bank_code', 'contract_unique_id', 'contract_no', 'repayment_plan_no', '2016-12-11 00:00:00', 1, 'trade_remark', 1, 'external_trade_serial_no', 'cash_flow_serial_no', 1, 1, 1, 1, 'trade_audit_result_remark', 1, 'cash_flow_audit_result_remark', '2016-10-22 00:00:00', '2016-11-11 00:00:00'),
	(4, 'external_trade_batch_detail_uuid3', 'external_trade_batch_uuid2', 'financial_contract_uuid', 1, 'external_batch_no', 'external_record_sn', 'external_record_unique_id', 'external_business_order_no', 11.00, NULL, 'currency', 'cp_name', 'cp_bank_card_no', 1, 'cp_bank_code', 'contract_unique_id', 'contract_no', 'repayment_plan_no', '2016-12-11 00:00:00', 1, 'trade_remark', 1, 'external_trade_serial_no', 'cash_flow_serial_no', 1, 1, 1, 2, 'trade_audit_result_remark', 1, 'cash_flow_audit_result_remark', '2016-10-22 00:00:00', '2016-11-11 00:00:00'),
	(1, 'external_trade_batch_detail_uuid', 'external_trade_batch_uuid', 'financial_contract_uuid', 1, 'external_batch_no', 'external_record_sn', 'external_record_unique_id', 'external_business_order_no', 11.00, NULL, 'currency', 'cp_name', 'cp_bank_card_no', 1, 'cp_bank_code', 'contract_unique_id', 'contract_no', 'repayment_plan_no', '2016-12-11 00:00:00', 1, 'trade_remark', 1, 'external_trade_serial_no', 'cash_flow_serial_no', 1, 2, 1, 1, 'trade_audit_result_remark', 1, 'cash_flow_audit_result_remark', '2016-10-22 00:00:00', '2016-11-11 00:00:00'),
	(5, 'external_trade_batch_detail_uuid4', 'external_trade_batch_uuid', 'financial_contract_uuid', 1, 'external_batch_no', 'external_record_sn', 'external_record_unique_id', 'external_business_order_no', 11.00, NULL, 'currency', 'cp_name', 'cp_bank_card_no', 1, 'cp_bank_code', 'contract_unique_id', 'contract_no', 'repayment_plan_no', '2016-12-11 00:00:00', 1, 'trade_remark', 1, 'external_trade_serial_no', 'cash_flow_serial_no', 1, 2, 1, 1, 'trade_audit_result_remark', 1, 'cash_flow_audit_result_remark', '2016-10-22 00:00:00', '2016-11-11 00:00:00'),
	(6, 'external_trade_batch_detail_uuid5', 'external_trade_batch_uuid', 'financial_contract_uuid', 1, 'external_batch_no', 'external_record_sn', 'external_record_unique_id', 'external_business_order_no', 11.00, NULL, 'currency', 'cp_name', 'cp_bank_card_no', 1, 'cp_bank_code', 'contract_unique_id', 'contract_no', 'repayment_plan_no', '2016-12-11 00:00:00', 1, 'trade_remark', 1, 'external_trade_serial_no', 'cash_flow_serial_no', 1, 2, 0, 1, 'trade_audit_result_remark', 1, 'cash_flow_audit_result_remark', '2016-10-22 00:00:00', '2016-11-11 00:00:00'),
	(7, 'external_trade_batch_detail_uuid6', 'external_trade_batch_uuid', 'financial_contract_uuid', 1, 'external_batch_no', 'external_record_sn', 'external_record_unique_id', 'external_business_order_no', 11.00, NULL, 'currency', 'cp_name', 'cp_bank_card_no', 1, 'cp_bank_code', 'contract_unique_id', 'contract_no', 'repayment_plan_no', '2016-12-11 00:00:00', 1, 'trade_remark', 1, 'external_trade_serial_no', 'cash_flow_serial_no', 1, 2, 0, 1, 'trade_audit_result_remark', 0, 'cash_flow_audit_result_remark', '2016-10-22 00:00:00', '2016-11-11 00:00:00');
	

SET FOREIGN_KEY_CHECKS=1;