package com.suidifu.dowjones.utils;


import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

public class ExtraChargeSpec implements Serializable {
    public static final String SND_UNEARNED_LOAN_ASSET_PRINCIPLE = "SND_UNEARNED_LOAN_ASSET_PRINCIPLE";
    public static final String SND_UNEARNED_LOAN_ASSET_INTEREST = "SND_UNEARNED_LOAN_ASSET_INTEREST";
    public static final Map<String, String> BANKSAVING_INDEPEND_ACCOUNT_AND_EXTRA_CHARGE_MAP = new HashMap<>();
    public static final Map<String, String> RECEIVABLE_ASSET_AND_EXTRA_CHARGE_MAP = new HashMap<>();
    //本金
    private static final String LOAN_ASSET_PRINCIPAL_KEY = "SND_UNEARNED_LOAN_ASSET_PRINCIPLE";
    //利息
    private static final String LOAN_ASSET_INTEREST_KEY = "SND_UNEARNED_LOAN_ASSET_INTEREST";
    private static final String TRD_RECEIVABLE_LOAN_ASSET_INTEREST = "TRD_RECIEVABLE_LOAN_ASSET_INTEREST";
    private static final String TRD_RECEIVABLE_OVERDUE_LOAN_ASSET_PRINCIPLE = "TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_PRINCIPLE";
    private static final String TRD_RECEIVABLE_OVERDUE_LOAN_ASSET_INTEREST = "TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_INTEREST";
    private static final String TRD_RECEIVABLE_LOAN_ASSET_PRINCIPLE = "TRD_RECIEVABLE_LOAN_ASSET_PRINCIPLE";
    private static final String TRD_BANK_SAVING_GENERAL_PRINCIPAL = "TRD_BANK_SAVING_GENERAL_PRINCIPAL";
    private static final String TRD_LIABILITIES_INDEPENDENT_REIMBURSE_PRINCIPAL = "TRD_LIABILITIES_INDEPENDENT_REIMBURSEL_PRINCIPAL";//独立账户偿付本金
    private static final String TRD_BANK_SAVING_GENERAL_INTEREST = "TRD_BANK_SAVING_GENERAL_INTEREST";
    private static final String TRD_LIABILITIES_INDEPENDENT_REIMBURSE_INTEREST = "TRD_LIABILITIES_INDEPENDENT_REIMBURSE_INTEREST";//独立账户偿付利息

    static {
        RECEIVABLE_ASSET_AND_EXTRA_CHARGE_MAP.put(TRD_RECEIVABLE_LOAN_ASSET_PRINCIPLE, LOAN_ASSET_PRINCIPAL_KEY);
        RECEIVABLE_ASSET_AND_EXTRA_CHARGE_MAP.put(TRD_RECEIVABLE_LOAN_ASSET_INTEREST, LOAN_ASSET_INTEREST_KEY);
        RECEIVABLE_ASSET_AND_EXTRA_CHARGE_MAP.put(TRD_RECEIVABLE_OVERDUE_LOAN_ASSET_PRINCIPLE, LOAN_ASSET_PRINCIPAL_KEY);
        RECEIVABLE_ASSET_AND_EXTRA_CHARGE_MAP.put(TRD_RECEIVABLE_OVERDUE_LOAN_ASSET_INTEREST, LOAN_ASSET_INTEREST_KEY);
        RECEIVABLE_ASSET_AND_EXTRA_CHARGE_MAP.put(SND_UNEARNED_LOAN_ASSET_PRINCIPLE, LOAN_ASSET_PRINCIPAL_KEY);
        RECEIVABLE_ASSET_AND_EXTRA_CHARGE_MAP.put(SND_UNEARNED_LOAN_ASSET_INTEREST, LOAN_ASSET_INTEREST_KEY);

        BANKSAVING_INDEPEND_ACCOUNT_AND_EXTRA_CHARGE_MAP.put(TRD_BANK_SAVING_GENERAL_PRINCIPAL, LOAN_ASSET_PRINCIPAL_KEY);
        BANKSAVING_INDEPEND_ACCOUNT_AND_EXTRA_CHARGE_MAP.put(TRD_LIABILITIES_INDEPENDENT_REIMBURSE_PRINCIPAL, LOAN_ASSET_PRINCIPAL_KEY);
        BANKSAVING_INDEPEND_ACCOUNT_AND_EXTRA_CHARGE_MAP.put(TRD_BANK_SAVING_GENERAL_INTEREST, LOAN_ASSET_INTEREST_KEY);
        BANKSAVING_INDEPEND_ACCOUNT_AND_EXTRA_CHARGE_MAP.put(TRD_LIABILITIES_INDEPENDENT_REIMBURSE_INTEREST, LOAN_ASSET_INTEREST_KEY);
        BANKSAVING_INDEPEND_ACCOUNT_AND_EXTRA_CHARGE_MAP.put(SND_UNEARNED_LOAN_ASSET_PRINCIPLE, LOAN_ASSET_PRINCIPAL_KEY);
        BANKSAVING_INDEPEND_ACCOUNT_AND_EXTRA_CHARGE_MAP.put(SND_UNEARNED_LOAN_ASSET_INTEREST, LOAN_ASSET_INTEREST_KEY);
    }

    private ExtraChargeSpec() {
    }
}