CREATE TABLE `general_balance` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_financial_contract_uuid` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_contract_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `bank_saving_loan` decimal(19,2) DEFAULT 0,
  `bank_saving_freeze` decimal(19,2) DEFAULT 0,
  `pay_able` decimal(19,2) DEFAULT 0,
  `create_time` datetime DEFAULT NULL,
  `lastest_modified_time` datetime DEFAULT NULL,
  `version_lock` varchar(255) COLLATE utf8_unicode_ci default 'version_lock',
  `int_field_1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `int_field_2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `int_field_3` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `string_field_1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `string_field_2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `string_field_3` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `decimal_field_1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `decimal_field_2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `decimal_field_3` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`) USING BTREE,
  UNIQUE KEY `related_financial_contract_uuid` (`related_financial_contract_uuid`) USING BTREE,
  INDEX(`related_financial_contract_uuid`) USING BTREE,
  INDEX(`uuid`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=34579 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='放款限额管理表';